language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - secure: "RXRr93fTs89A7D/BvK5s2SnnvdsGgedjHBBfQjzChP3J/sgVQ0sAK9krqJ3HL45dR2nCxJ7JKJRdwWVB2ZurihzAoCXt5c/R8D5MdlW56KaI7fPLhyXSV9vm4c3NMRYS22gXbPWjK6y41tNMSeyIarjYROBMJXf8oC67E7QVivw="
    - GH_REPO: github.com/locomotivemtl/charcoal-project-boilerplate.git

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: nightly

before_script:
  ## Init composer
  - composer selfupdate --quiet
  - COMPOSER_ROOT_VERSION=dev-master composer install -n --dev

  ## Create temporary folders
  - mkdir -p build/logs\

script:
  ## Lint PHP Files
  - find {src,tests} -name '*.php' -print0 | xargs -0 -n1 -P8 php -l | grep -v '^No syntax errors detected'; test $? -eq 1

  ## PHP Code Sniffer
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1;./vendor/bin/phpcs -ps --colors --standard=phpcs.xml src/; fi

  ## Run PHPUnit Tests
  - phpunit --configuration ./tests/phpunit.xml --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - bash build/travis/phpdoc_ghpages.sh
  - bash build/travis/apigen_ghpages.sh

notifications:
  slack: locomotivemtl:d9h8ZWwTZ6b3WUsSP9s26nb1
  email: charcoal@locomotive.ca
